export const AUTHENTICATE_USER = "AUTHENTICATE_USER"
export const SIGN_OUT = "SIGN_OUT"

export const RECEIVE_QUESTIONS = "RECEIVE_QUESTIONS"
export const ADD_QUESTION = "ADD_QUESTION"

export const RECEIVE_USERS = "RECEIVE_USERS"